# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  run_on_arm64:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v3

       - name: Set up Go
         uses: actions/setup-go@v3
         with:
           go-version: 1.19
         
       - name: Run on aarch64
         uses: uraimo/run-on-arch-action@v2
         with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          install: |
              apt-get update && \
              apt-get install -y wget && \
              apt-get install -y git && \
              wget https://go.dev/dl/go1.19.linux-arm64.tar.gz && \
              rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.linux-arm64.tar.gz && \
              rm go1.19.linux-arm64.tar.gz && \
              export PATH=$PATH:/usr/local/go/bin && \
              export PS1="\u@\h:\w\$ " && \ 
              source $HOME/.bashrc
     
          run: |
            go build -buildvcs=false ./...
            go test -v ./... 
